In [2]:
import numpy as np

2.1 Scalars, Vectors, Matrices and Tensors

In [2]:
#행렬 생성
data = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(data)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr.ndim

2

In [4]:
arr.shape

(3, 3)

In [5]:
#전치행렬(transpose)
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
#행렬 덧셈
arr2 = np.ones((3,3))
print(arr2)
print(arr+arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


2.2 Multiplying Matrices and Vectors

In [9]:
#아다마르 곱(Hadamard product)
arr = np.array([[1,2,3],[4,5,6]])
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
# 행렬 곱(multiplication)
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]


In [12]:
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [13]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [14]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

2.3 Identity and Inverse Matrices

In [17]:
A = np.array([[1,-1,-3],[2,4,5],[6,0,-3]])
B = np.linalg.inv(A)
print(B)
print(np.dot(A,B))

[[-0.5        -0.125       0.29166667]
 [ 1.5         0.625      -0.45833333]
 [-1.         -0.25        0.25      ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2.4 Linear Dependence and Span

2.5 Norms

In [3]:
a = np.arange(9) - 4
b = a.reshape((3, 3))
print(a)
print(b)
#Euclidean norm 
print(np.linalg.norm(a))
#Frobenius norm
print(np.linalg.norm(b))
print(np.linalg.norm(b,'fro'))
#max norm
print(np.linalg.norm(a, np.inf))
print(np.linalg.norm(b, np.inf)) #max(sum(abs(x), axis=1))
print(np.linalg.norm(b, 1)) #max(sum(abs(x), axis=0))

[-4 -3 -2 -1  0  1  2  3  4]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
7.745966692414834
7.745966692414834
7.745966692414834
4.0
9.0
7.0


2.6 Special Kinds of Matrices and Vectors

In [19]:
#orthonormal = orthogonal + unitnorm
# A.T.dot(A) = A.dot(A.T) = I
A = np.array([[1/3, 2/3, -2/3],[-2/3, 2/3, 1/3],[2/3, 1/3, 2/3]])
print(A)
print(A.T.dot(A))
print(A.dot(A.T))

[[ 0.33333333  0.66666667 -0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.66666667  0.33333333  0.66666667]]
[[ 1.00000000e+00  1.54197642e-17 -2.46716228e-17]
 [ 1.54197642e-17  1.00000000e+00 -1.23358114e-17]
 [-2.46716228e-17 -1.23358114e-17  1.00000000e+00]]
[[ 1.00000000e+00 -1.54197642e-17  2.46716228e-17]
 [-1.54197642e-17  1.00000000e+00 -1.23358114e-17]
 [ 2.46716228e-17 -1.23358114e-17  1.00000000e+00]]


2.7 Eigendecomposition

In [21]:
# 대각화(eigendecomposition)
# A = V.dot(lambdas).dot(V_inv)
A = np.array([[5,1],[3,3]])
np.linalg.eig(A)

(array([6., 2.]),
 array([[ 0.70710678, -0.31622777],
        [ 0.70710678,  0.9486833 ]]))

In [22]:
lambdas = np.diag([6., 2.])
V = np.array([[ 0.70710678, -0.31622777],
        [ 0.70710678,  0.9486833 ]])
V_inv = np.linalg.inv(V)
V.dot(lambdas).dot(V_inv)

array([[4.99999999, 1.00000001],
       [2.99999999, 3.00000001]])

2.8 Singluar Value Decomposition

In [34]:
A = np.array([[7, 2], [3, 4], [5, 3]])
print(A)
U, D, V = np.linalg.svd(A)
print(U)
print(D)
print(V)
print(np.dot(U[:, :2] * D, V))

[[7 2]
 [3 4]
 [5 3]]
[[-0.69366543  0.59343205 -0.40824829]
 [-0.4427092  -0.79833696 -0.40824829]
 [-0.56818732 -0.10245245  0.81649658]]
[10.25142677  2.62835484]
[[-0.88033817 -0.47434662]
 [ 0.47434662 -0.88033817]]
[[7. 2.]
 [3. 4.]
 [5. 3.]]


2.9 The Moore-Penrose Pseudoinverse

In [42]:
A = np.array([[7, 2], [3, 4], [5, 3]])
B = np.linalg.pinv(A)
print(A)
print(A.dot(B).dot(A))

[[7 2]
 [3 4]
 [5 3]]
[[7. 2.]
 [3. 4.]
 [5. 3.]]


2.10 The Trace Operator

In [48]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print(np.trace(x))
np.trace(x.dot(y)) == np.trace(y.dot(x))

6


True